FLAGS = -Wall -Wextra -Werror -pedantic



# Makefile for programming challenges
#
# CSCI 21, Spring 2014
#
# Programmer: Stacy A. Rios-Jimenez
#


# Target for programming project 1
# Date completed: 2-21-2014
Project1: Project1.cpp
	g++ $(FLAGS) Project1.cpp -o Project1